version: '2'
services:
    erkdemo-app:
        image: erkdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://erkdemo-mysql:3306/erkdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    erkdemo-mysql:
        extends:
            file: mysql.yml
            service: erkdemo-mysql
